export const REGISTER_START = "REGISTER_START"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"


export const LOGOUT_START = "LOGOUT_START"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const GOOGLE_SIGNIN_START = "GOOGLE_SIGNIN_START"
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS"
export const GOOGLE_SIGNIN_FAIL = "GOOGLE_SIGNIN_FAIL"

export const FB_SIGNIN_START = "FB_SIGNIN_START"
export const FB_SIGNIN_SUCCESS = "FB_SIGNIN_SUCCESS"
export const FB_SIGNIN_FAIL = "FB_SIGNIN_FAIL"

export const GET_AUTH_START = "GET_AUTH_START"
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS"
export const GET_AUTH_FAIL = "GET_AUTH_FAIL"

export const RESET_PASSWORD_START = "RESET_PASSWORD_START"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"